CREATE DATABASE ESCUELAM;
USE ESCUELAM;

CREATE TABLE EMPLEADOS (
RFC_EMP VARCHAR (13) NOT NULL PRIMARY KEY,
FOREIGN KEY (MATRICULA) REFERENCES AUTOS_ASIGNADOS (MATRICULA),
NOMB_EMP VARCHAR (10) NOT NULL,
AP_EMP VARCHAR (10) NOT NULL,
AM_EMP VARCHAR (10) NOT NULL,
PUESTO VARCHAR (20) NOT NULL,
SEXO ENUM ('MASCULINO', 'FEMENINO') NOT NULL,
FECHA_NAC DATE NOT NULL,
TEL_PERSONAL INT NOT NULL,
CALLE VARCHAR (20) NOT NULL,
NUMERO INT NOT NULL,
COLONIA VARCHAR (30) NOT NULL,
ALCALDIA VARCHAR (20) NOT NULL
);

CREATE TABLE CONTRATACION (
TIPO_CONTRATACION VARCHAR (10) NOT NULL PRIMARY KEY,
PRECIO INT NOT NULL,
DESC_BENEFICIOS VARCHAR (50) NOT NULL
);

CREATE TABLE AUTOS_ASIGNADOS (
MATRICULA VARCHAR (10) NOT NULL PRIMARY KEY,
FOREIGN KEY (RFC_EMP) REFERENCES EMPLEADOS (RFC_EMP),
MODELO VARCHAR (20) NOT NULL,
ANIO DATE, 
COLOR VARCHAR (20),
FECHA_ULT_INSP DATE,
ESTATUS ENUM ('DISPONIBLE', 'NO DISPONIBLE', 'BAJA') NOT NULL
);

CREATE TABLE CLIENTES (
RFC_CLIENTE VARCHAR (13) NOT NULL PRIMARY KEY,
FOREIGN KEY (TIPO_CONTRATACION) REFERENCES CONTRATACION (TIPO_CONTRATACION),
NOMB_CLI VARCHAR (10) NOT NULL,
AP_CLI VARCHAR (10) NOT NULL,
AM_CLI VARCHAR (10) NOT NULL,
FECHA_NAC DATE NOT NULL,
CALLE VARCHAR (20) NOT NULL,
NUMERO INT NOT NULL,
COLONIA VARCHAR (30) NOT NULL,
ALCALDIA VARCHAR (20) NOT NULL,
PERMISO ENUM ('SI', 'NO', 'EN TRÁMITE'),
OBSERVACIONES VARCHAR (30),
TOTAL_PAGO INT NOT NULL,
PAGO1 INT,
PAGO2 INT,
ADEUDO INT,
USUARIO VARCHAR (30) NOT NULL,
DOMINIO VARCHAR (20) NOT NULL
);

CREATE TABLE AGENDA (
FECHA DATE NOT NULL,
HORA TIME NOT NULL, 
FOREIGN KEY (RFC_EMP) REFERENCES EMPLEADOS (RFC_EMP),
PRIMARY KEY (FECHA, HORA, RFC_EMP),
ACTIVIDAD ENUM ('EXAMEN', 'LECCIÓN'),
KM_RECORRIDOS INT,
NOTAS VARCHAR (50),
EXAM_TEO INT,
EXAM_PRAC INT,
NOTAS_RESULTADO VARCHAR (50)
);

# USUARIO ES EL NOMBRE DEL EMPLEADO Y LA CONTRASEÑA RFC
INSERT INTO EMPLEADOS (RFC_EMP, NOB_EMP, AP_EMP, AM_EMP, PUESTO, SEXO, FECHA_NAC, TEL_PERSONAL, CALLE, NUMERO, COLONIA, ALCALDIA) 
VALUES ('MOSE030526A50', 'ERICK', 'MONROY', 'SANTANA', 'SUPERVISOR', 'MASCULINO', '2003-05-26', '5540608099', 'LAS FLORES', 9, 'PASCUAL', 'IZTACALCO');

